
stages:
  - build
  - deploy

build:linux:amd64:
  stage: build
  tags:
    - docker-capsule-64
  script:
    - node release/ci-compile.js linux amd64
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week

build:linux:386:
  stage: build
  tags:
    - docker-capsule-32
  script:
    - node release/ci-compile.js linux 386
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week

build:windows:
  stage: build
  tags:
    - windows
  script:
    - node release/ci-compile.js windows 386
    - node release/ci-compile.js windows amd64
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week

build:darwin:amd64:
  stage: build
  tags:
    - darwin
  script:
    - node release/ci-compile.js darwin amd64
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week

deploy:
  stage: deploy
  tags:
    - dropsy
  script:
    - /bin/sh release/ci-deploy.sh
